### ISSUE TITLE
Feature: Bonus votes against players in votecounter

### ISSUE THREAD

**Issue by BridgeSync** [JacksonVirgo/mafia-engine-2.0#94]
> Posted by **@lunex**
> <sub>1292651510899146814</sub>

Add a way to give players bonus votes against them to the votecounter.
When a player receives a bonus votes against them they have one vote against them at all times.
Ex.: The day just started, and a player has a bonus vote against them, majority is 5, but due to the bonus vote, just 4 players voting this player are enough for a hammer to occur.

In other words, the bonus vote singifies that the affected player requires one less vote to be hammered, and will require another player to have one more vote than usual in order to not die to a plurality execution.
Ex.: Two players are voted by 3 players each (they have 3 votes against them each) however, one of the two players also has a bonus vote against them, this means this player actually has 4 votes against himself (3 from voters + 1 bonus vote) which would result in this player dying in case the tie is still present at EoD.

ex. of VC layout..

```yaml
Day 2 Votecount 3

that_amnesiac:                   2 [+1] - Free's alt 
bigscaryblackman69:              1      - stella.9986 
Sprigatito (on the Clocktower):  5      - bigscaryblackman69 , dangerous_luka , that_amnesiac , QueenOfCheetahs , mrrfiish 

Abstaining:                      2      - 53R0 (Zero) , Sprigatito (on the Clocktower) 

- - - - -

With 9 players, majority is 5 votes
```

This specific ideas for it would require for there to be 4 extra spaces everywhere where the "[+1]" isn't added, while adding the correct integer in brackets with a symbolic "+" to indicate that it's an extra vote against that person.
